### PR TITLE
StructureFrontEnd

### PR DESCRIPTION
**Pull request by canilo1**
Potential rough draft for front end(Its not finalized and can be edited, Just my idea. Good structure for the week(Wont be here for the rest of the week,untill friday evening)(Check slack for my more detailed messege)

### CODE REVIEW

**Comment by OGoncharenko** [comment]
How about creating a "components" folder and inside it add two different folders for Teacher and Student? Where will be pages for these two users: Teacher and Student. Also, I think MainPage should be inside "components" too, not in src.

**Comment by lauradurandv** [comment]
my-app/
├── node_modules/
├── public/
│   ├── favicon.ico
│   ├── index.html
│   └── ...
├── src/
│   ├── assets/
│   │   ├── fonts/
│   │   ├── images/
│   │   └── ...
│   ├── components/
│   │   ├── common/
│   │   │   ├── Button/
│   │   │   ├── Header/
│   │   │   └── ...
│   │   ├── pages/
│   │   │   ├── student/
|   |   |                     |---- studentDashboard
│   │   │   ├── teacher/
|   |   |                     |---- teacherDashboard
│   │   │   └── ...
│   │  └── ...

how about a combination ?

**Comment by OGoncharenko** [comment]
Monosnap react-todo:src at main · OGoncharenko:react-todo 2024-08-06 11-53-03
In my mind it looks like this

**Comment by ElijahMSmith** [comment]
I am not in favor of creating files that we aren't using yet and are empty. They just put us into a tiny little contract that we might decide we want to break once we actually write some code. That said, this is a good discussion to have and let's figure this out in Slack!

**Pull request closed without merging**
